version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/
hooks:
  BeforeInstall:
    - location: /home/ubuntu/scripts/install_dependencies.sh
    - location: /home/ubuntu/scripts/setup_nginx.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /home/ubuntu/scripts/run_app.sh
    - location: /home/ubuntu/scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: /home/ubuntu/scripts/stop_server.sh
      timeout: 300
      runas: root
