version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 3000
      runas: root
  Install:
    - location: scripts/install
      timeout: 3000
      runas: ubuntu
  AfterInstall:
    - location: scripts/setup_nginx    
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/run_app
      timeout: 3000
      runas: ubuntu
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
