version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - d1=`date +%s`
      - apt-get update -y
      - apt-get install -y maven
      - apt-get install -y default-jdk
    finally:
      - d2=`date +%s`
      - echo Install phase took $(date --date=@$(($d2 - $d1)) +'%M minutes, %s seconds') 
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - d1=`date +%s`
      - cd src
      - mvn -DskipTest clean install
    finally:
      - d2=`date +%s`
      - echo Build phase took $(date --date=@$(($d2 - $d1)) +'%M minutes, %s seconds') 

artifacts:
  files:
    - '/root/.m2'       #build respository
    - 'src/web/app/**'  #main app folder
    - 'scripts/**'      #scripts folder
    - 'nginx/**'        #NGINX folder
    - 'appspec.yml'     #APPSPEC for codedeploy service
  