version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - d1=`date +%s`
      - apt-get update -y
      - apt-get install -y maven
      - apt-get install -y default-jdk
    finally:
      - d2=`date +%s`
      - echo Install phase took $(date --date=@$(($d2 - $d1)) +'%s seconds') 
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - d1=`date +%s`
      - cd src
      - mvn clean install
    finally:
      - d2=`date +%s`
      - echo Build phase took $(date --date=@$(($d2 - $d1)) +'%s seconds') 
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
    finally:
      - echo  This always runs even if the post_build command fails
      - echo Entered the run phase...
      - cd web/app
      - ls

artifacts:
  files:
    - '**/*'
  base-directory: 'src/web/app'