version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - d1=`date +%s`
      - wget https://github.com/davidfoerster/aptsources-cleanup/releases/download/v0.1.7.5.2/aptsources-cleanup.pyz
      - chmod +x aptsources-cleanup.pyz
      - ./aptsources-cleanup.pyz -y
      - apt-get update -y
      - apt-get install -y maven
      - apt-get install -y default-jdk
    finally:
      - d2=`date +%s`
      - echo Install phase took $(date --date=@$(($d2 - $d1)) +'%M minutes, %s seconds') 
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - d1=`date +%s`
      - find ./ -type f -exec sed -i -e 's/1.7-SNAPSHOT/1.6.0/g' {} \;
      - cd src
      - mvn -DskipTests clean install #TOMODIFY
    finally:
      - d2=`date +%s`
      - echo Build phase took $(date --date=@$(($d2 - $d1)) +'%M minutes, %s seconds') 

artifacts:
  files:
    - '/root/.m2'       #build respository
    - 'src/**'          #main src folder
    - 'scripts/**'      #scripts folder
    - 'nginx/**'        #NGINX folder
    - 'appspec.yml'     #APPSPEC for codedeploy service
  