#!/bin/bash
echo "Installing dependencies..."
sudo apt-get -y update
sudo apt-get install -y nginx
sudo apt-get install -y maven
sudo apt-get install -y default-jdk
sudo apt-get install -y wget
sudo apt-get install -y ruby-full

echo "Build Project"
sudo mvn -DskipTest clean install
